### ISSUE TITLE
Loading large dataset 

### ISSUE THREAD

**Issue by Aayushktyagi** [sayakpaul/SimCLR-in-TensorFlow-2#1]
Hey Sayak,

Thanks for sharing code. I am trying Simclr with a larger dataset. 
I am using from_generator to load data where image_gen is imagedatagenerator.
I checked the notebook you shared here (https://github.com/tensorflow/tensorflow/issues/33535). It seems the below method works well when using model.fit whereas for custom training its is stuck infinitely. 
Just wanted to check have you came cross similar case. If yes can you share what might be the solution.
``` python
train_ds = tf.data.Dataset.from_generator(lambda: image_gen.flow_from_dataframe(dataframe=train_df,
                                             directory=None,
                                             x_col='path',
                                             y_col='labels',
                                             class_mode='categorical',
                                             batch_size=batch_size,
                                             classes=labels,
                                             target_size=(image_size, image_size)) , 
                                            output_types=(tf.float32, tf.float32),
                                            output_shapes=([None, image_size, image_size, 3],
                                            [None, 13]))

train_ds = (
    train_ds
    .shuffle(1024)
    .prefetch(tf.data.experimental.AUTOTUNE)
)

```

Thanks 
Aayush

**Comment by sayakpaul** [comment]
@Aayushktyagi thanks for reaching out. If you are using `tf.data` I would suggest using it to the fullest especially when you are dealing with a custom training situation. [Here's](https://sayak.dev/tf.keras/data_augmentation/image/2020/05/10/augmemtation-recipes.html#TensorFlow-image-ops-with-tf.data-APIs) an example. 

It would be even more performant if you first convert your dataset to TF Records and then build your input pipeline with `tf.data`. Find an example [here](https://colab.research.google.com/drive/1A3TALnuDj0FXqvSBM96Es6BEKaZwbkVz). 

I hope that helps.
