### ISSUE TITLE
notebook of Linear evaluation,  loss: 1953.4716 and val_loss: 1460.1127 !!!

### ISSUE THREAD

**Issue by aynesss** [sayakpaul/SimCLR-in-TensorFlow-2#10]
After running your notebook of Linear evaluation, I find this error 
` ValueError: Layer sequential expects 1 input(s), but it received 2 input tensors. Inputs received: [<tf.Tensor 'IteratorGetNext:0' shape=(None, 128) dtype=float32>, <tf.Tensor 'ExpandDims:0' shape=(None, 1) dtype=int64>] `

**Comment by sayakpaul** [comment]
Weird. All the notebooks in this repository are extensively tested to ensure they are error-free. I would recommend providing your notebook as a Colab Notebook here so that I can see the error and its origin.

**Comment by aynesss** [comment]
Sorry, I make a typing error.
But I found loss : loss: 1953.4716 and val_loss: 1460.1127  !!!

**Comment by sayakpaul** [comment]
You might have forgotten to scale the pixels.

**Comment by aynesss** [comment]
when I write 
`for image in X_train:`
    `print(image.size)`
It display :
150528

So what I must add to the code

**Comment by sayakpaul** [comment]
Now it's becoming a bit weird for me honestly. I have mentioned a couple of resources for you that would be easier for you to go through. Those resources will help you to get through the basics and you might be able to also figure what's going wrong.
