### ISSUE TITLE
"SimCLR_ImageNet_Subset.ipynb" in Colab (InvalidArgumentError) Pls help!

### ISSUE THREAD

**Issue by chho-work** [sayakpaul/SimCLR-in-TensorFlow-2#2]
Hi Sayak,

Thanks for sharing the code!
I ran into the below issue when running "SimCLR_ImageNet_Subset.ipynb" in Colab.
Running the first cell under the "Training", I got this error.  All other previous cells were executed flawlessly!

=====================================================================================
0%|          | 0/200 [00:04<?, ?it/s]
---------------------------------------------------------------------------
_FallbackException                        Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_array_ops.py in tile(input, multiples, name)
  11035         _ctx._context_handle, tld.device_name, "Tile", name, tld.op_callbacks,
> 11036         input, multiples)
  11037       return _result

_FallbackException: This function does not handle the case of the path where all inputs are not already EagerTensors.

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
15 frames
<ipython-input-19-83fbe29a21df> in <module>()
      9 
     10 epoch_wise_loss, resnet_simclr  = train_simclr(resnet_simclr_2, train_ds, optimizer, criterion,
---> 11                  temperature=0.1, epochs=200)
     12 
     13 with plt.xkcd():

<ipython-input-18-c2112938694d> in train_simclr(model, dataset, optimizer, criterion, temperature, epochs)
      7         for image_batch in dataset:
      8             a = data_augmentation(image_batch)
----> 9             b = data_augmentation(image_batch)
     10 
     11             loss = train_step(a, b, model, optimizer, criterion, temperature)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, *args, **kwargs)
    966           with base_layer_utils.autocast_context_manager(
    967               self._compute_dtype):
--> 968             outputs = self.call(cast_inputs, *args, **kwargs)
    969           self._handle_activity_regularization(inputs, outputs)
    970           self._set_mask_metadata(inputs, outputs, input_masks)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py in call(self, inputs, training, mask)
    289         kwargs['training'] = training
    290 
--> 291       outputs = layer(inputs, **kwargs)
    292 
    293       if len(nest.flatten(outputs)) != 1:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, *args, **kwargs)
    966           with base_layer_utils.autocast_context_manager(
    967               self._compute_dtype):
--> 968             outputs = self.call(cast_inputs, *args, **kwargs)
    969           self._handle_activity_regularization(inputs, outputs)
    970           self._set_mask_metadata(inputs, outputs, input_masks)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/core.py in call(self, inputs, mask, training)
    886     with backprop.GradientTape(watch_accessed_variables=True) as tape,\
    887         variable_scope.variable_creator_scope(_variable_creator):
--> 888       result = self.function(inputs, **kwargs)
    889     self._check_variables(created_variables, tape.watched_variables())
    890     return result

<ipython-input-8-4cd0bcc3a7e8> in __call__(self, sample)
     10         # Randomly apply transformation (color distortions) with probability p.
     11         sample = self._random_apply(self._color_jitter, sample, p=0.8)
---> 12         sample = self._random_apply(self._color_drop, sample, p=0.2)
     13 
     14         return sample

<ipython-input-8-4cd0bcc3a7e8> in _random_apply(self, func, x, p)
     34                   tf.cast(p, tf.float32)),
     35           lambda: func(x),
---> 36           lambda: x)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/control_flow_ops.py in cond_for_tf_v2(pred, true_fn, false_fn, name)
   1390 
   1391   """
-> 1392   return cond(pred, true_fn=true_fn, false_fn=false_fn, strict=True, name=name)
   1393 
   1394 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py in new_func(*args, **kwargs)
    505                 'in a future version' if date is None else ('after %s' % date),
    506                 instructions)
--> 507       return func(*args, **kwargs)
    508 
    509     doc = _add_deprecated_arg_notice_to_docstring(

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/control_flow_ops.py in cond(pred, true_fn, false_fn, strict, name, fn1, fn2)
   1203     if context.executing_eagerly():
   1204       if pred:
-> 1205         result = true_fn()
   1206       else:
   1207         result = false_fn()

<ipython-input-8-4cd0bcc3a7e8> in <lambda>()
     33           tf.less(tf.random.uniform([], minval=0, maxval=1, dtype=tf.float32),
     34                   tf.cast(p, tf.float32)),
---> 35           lambda: func(x),
     36           lambda: x)

<ipython-input-8-4cd0bcc3a7e8> in _color_drop(self, x)
     26     def _color_drop(self, x):
     27         x = tf.image.rgb_to_grayscale(x)
---> 28         x = tf.tile(x, [1, 1, 3])
     29         return x
     30 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_array_ops.py in tile(input, multiples, name)
  11039       try:
  11040         return tile_eager_fallback(
> 11041             input, multiples, name=name, ctx=_ctx)
  11042       except _core._SymbolicException:
  11043         pass  # Add nodes to the TensorFlow graph.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_array_ops.py in tile_eager_fallback(input, multiples, name, ctx)
  11079   _attrs = ("T", _attr_T, "Tmultiples", _attr_Tmultiples)
  11080   _result = _execute.execute(b"Tile", 1, inputs=_inputs_flat, attrs=_attrs,
> 11081                              ctx=ctx, name=name)
  11082   if _execute.must_record_gradient():
  11083     _execute.record_gradient(

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

InvalidArgumentError: Expected multiples argument to be a vector of length 4 but got length 3 [Op:Tile]

================================================================================
Pls kindly help me to solve this issue!  Many thanks!

Chua-Hsien Ho

**Comment by sayakpaul** [comment]
@chho-work thanks for reporting the issue. I just fixed it up. You should be good to go now.

**Comment by chho-work** [comment]
Thanks for you prompt reply!  The error is gone!  

Now I am getting a new error:

====================================================================================
0%|          | 0/200 [00:00<?, ?it/s]
---------------------------------------------------------------------------
ResourceExhaustedError                    Traceback (most recent call last)
<ipython-input-21-83fbe29a21df> in <module>()
      9 
     10 epoch_wise_loss, resnet_simclr  = train_simclr(resnet_simclr_2, train_ds, optimizer, criterion,
---> 11                  temperature=0.1, epochs=200)
     12 
     13 with plt.xkcd():

7 frames
<ipython-input-20-c2112938694d> in train_simclr(model, dataset, optimizer, criterion, temperature, epochs)
      9             b = data_augmentation(image_batch)
     10 
---> 11             loss = train_step(a, b, model, optimizer, criterion, temperature)
     12             step_wise_loss.append(loss)
     13 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    578         xla_context.Exit()
    579     else:
--> 580       result = self._call(*args, **kwds)
    581 
    582     if tracing_count == self._get_tracing_count():

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    642         # Lifting succeeded, so variables are initialized and we can run the
    643         # stateless function.
--> 644         return self._stateless_fn(*args, **kwds)
    645     else:
    646       canon_args, canon_kwds = \

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in __call__(self, *args, **kwargs)
   2418     with self._lock:
   2419       graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
-> 2420     return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
   2421 
   2422   @property

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in _filtered_call(self, args, kwargs)
   1663          if isinstance(t, (ops.Tensor,
   1664                            resource_variable_ops.BaseResourceVariable))),
-> 1665         self.captured_inputs)
   1666 
   1667   def _call_flat(self, args, captured_inputs, cancellation_manager=None):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1744       # No tape is watching; skip to running the function.
   1745       return self._build_call_outputs(self._inference_function.call(
-> 1746           ctx, args, cancellation_manager=cancellation_manager))
   1747     forward_backward = self._select_forward_and_backward_functions(
   1748         args,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in call(self, ctx, args, cancellation_manager)
    596               inputs=args,
    597               attrs=attrs,
--> 598               ctx=ctx)
    599         else:
    600           outputs = execute.execute_with_cancellation(

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

ResourceExhaustedError:  OOM when allocating tensor with shape[64,512,7,7] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node model_1/resnet50/conv5_block3_2_bn/FusedBatchNormV3 (defined at <ipython-input-18-0c36dcded546>:5) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
 [Op:__inference_train_step_22781]

Function call stack:
train_step

====================================================================================
