### ISSUE TITLE
Difference between notebook

### ISSUE THREAD

**Issue by aynesss** [sayakpaul/SimCLR-in-TensorFlow-2#5]
Please I can't undrestand difference between this notebook : https://github.com/sayakpaul/SimCLR-in-TensorFlow-2/blob/master/Supervised_Full_Dataset.ipynb 
and the other one : https://github.com/sayakpaul/SimCLR-in-TensorFlow-2/blob/master/Linear_Evaluation_Imagenet_Subset.ipynb

**Comment by sayakpaul** [comment]
The first takes the representations of a ResNet50 pre-trained using SimCLR and runs linear evaluation. 

The second initializes an empty ResNet50 and trains using conventional supervised learning.

**Comment by aynesss** [comment]
@sayakpaul  thank you very much for your answer.. can you tell me please , what this line do 
`wandb.log({"nt_xentloss": np.mean(step_wise_loss)})`
I would like to change it to save result on my own folder, I don't require to visualize result.. 
How can I remove this and replace it. Thanks

**Comment by sayakpaul** [comment]
`wandb` is a Python library that helps track ML experiments. Find out more here: https://wandb.ai/.

**Comment by aynesss** [comment]
Thanks a lot,
Please can you tell me for what those lines:

`le = LabelEncoder()`
`y_train_enc = le.fit_transform(y_train)`
`y_test_enc = le.transform(y_test)`

**Comment by sayakpaul** [comment]
`LabelEncoder`: http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html
