### ISSUE TITLE
base_model.trainable = True

### ISSUE THREAD

**Issue by aynesss** [sayakpaul/SimCLR-in-TensorFlow-2#9]
I find that you use `base_model.trainable = True` and after that  `features = base_model(inputs, training=False) `. Can you explain to me why ?

**Comment by sayakpaul** [comment]
I will suggest going through the following guide to know more about these: https://keras.io/guides/transfer_learning/. 

It seems like you are not familiar with TensorFlow/Keras. Knowing their basics will be very helpful.
